apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pagamento-backend
  labels:
    cloud.googleapis.com/location: southamerica-east1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/minScale: '0'
    run.googleapis.com/max-surge: '0'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:     
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 91827266597-compute@developer.gserviceaccount.com
      containers:
      - name: pagamento-backend
        image: southamerica-east1-docker.pkg.dev/fiap-tech-challenge-5soat/fiap-docker/pagamento-backend:latest
        ports:
        - name: http1
          containerPort: 31301
        env:
          - name: PROJECT_ID
            value: fiap-tech-challenge-5soat
          - name: REGION
            value: southamerica-east1        
          - name: MERCADOPAGO_URL
            value: https://api.mercadopago.com/
          - name: MERCADOPAGO_USERID
            value: "84967632"
          - name: MERCADOPAGO_TOKEN
            value: TEST-2407420594039251-030222-bec9539a6ba5cae720b4f6d07ad3bd7a-84967632
          - name: MERCADOPAGO_POS
            value: SUC001
          - name: MERCADOPAGO_WEBHOOK_URL
            value: https://pagamento-backend-91827266597.southamerica-east1.run.app
          - name: VERSAO
            value: "09"            
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: latest
                name: MONGODB_URL          
        resources:
          limits:
            cpu: '1000m'
            memory: '512Mi'
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 31301
  traffic:
  - percent: 100
    latestRevision: true